# Generated by Django 4.1.7 on 2023-03-30 22:48

import button.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ethereum_address",
                    models.CharField(
                        max_length=256,
                        validators=[button.models.validate_ethereum_address],
                    ),
                ),
                ("text", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
