# Generated by Django 4.1.7 on 2023-04-03 00:10

import button.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erc20", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ethereum_address",
                    models.CharField(
                        help_text="The Ethereum address to delegate to",
                        max_length=256,
                        validators=[button.models.validate_ethereum_address],
                    ),
                ),
                ("name", models.CharField(help_text="Name of button", max_length=256)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of button", max_length=256
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text to display on button", max_length=256
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        help_text="Hex color code, e.g. #000000",
                        max_length=7,
                        validators=[button.models.validate_hex_color],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        help_text="Hex color code, e.g. #FFFFFF",
                        max_length=7,
                        validators=[button.models.validate_hex_color],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "tokens",
                    models.ManyToManyField(
                        blank=True, help_text="Tokens to delegate", to="erc20.erc20"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet to delegate to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
