# Generated by Django 4.1.7 on 2023-03-31 11:34

import button.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erc20", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ethereum_address",
                    models.CharField(
                        help_text="The Ethereum address to delegate to",
                        max_length=256,
                        validators=[button.models.validate_ethereum_address],
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        default="Delegate",
                        help_text="Text to display on button",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "hex_color",
                    models.CharField(
                        blank=True,
                        default="#000000",
                        help_text="Hex color code, e.g. #000000",
                        max_length=7,
                        null=True,
                        validators=[button.models.validate_hex_color],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "tokens",
                    models.ManyToManyField(
                        blank=True, help_text="Tokens to delegate", to="erc20.erc20"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
