# Generated by Django 4.1.7 on 2023-03-31 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("button", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="button",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
