# Generated by Django 4.1.7 on 2023-03-31 21:06

import button.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("button", "0002_alter_button_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="button",
            old_name="hex_color",
            new_name="primary_color",
        ),
        migrations.AddField(
            model_name="button",
            name="name",
            field=models.CharField(
                blank=True,
                default="Untitled",
                help_text="Name of button",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="button",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                default="#FFFFFF",
                help_text="Hex color code, e.g. #FFFFFF",
                max_length=7,
                null=True,
                validators=[button.models.validate_hex_color],
            ),
        ),
    ]
