# Generated by Django 4.1.7 on 2023-03-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("button", "0003_rename_hex_color_button_primary_color_button_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="button",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of button", max_length=256, null=True
            ),
        ),
    ]
