# Generated by Django 4.1.7 on 2023-03-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERC20",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ethereum_address", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("decimals", models.IntegerField()),
                ("total_supply", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
