# Generated by Django 4.1.7 on 2023-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erc20", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="erc20",
            name="total_supply",
        ),
        migrations.AddField(
            model_name="erc20",
            name="chain_id",
            field=models.IntegerField(default=1),
        ),
    ]
