# Generated by Django 4.1.7 on 2023-03-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erc20", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="erc20",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterUniqueTogether(
            name="erc20",
            unique_together={("ethereum_address", "chain_id")},
        ),
    ]
