# Generated by Django 4.1.7 on 2023-03-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erc20", "0002_remove_erc20_total_supply_erc20_chain_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="erc20",
            name="created",
        ),
        migrations.RemoveField(
            model_name="erc20",
            name="updated",
        ),
    ]
